chore/MSSDK-1740: migrate npm to pnpm (#371)
* chore/MSSDK-1740: migrate npm to pnpm

* chore/MSSDK-1740: migrate npm to pnpm

* chore/MSSDK-1740: fix commit message verification script

* chore/MSSDK-1740: run prettier for README.md

* chore/MSSDK-1740: remove the preinstall script

* chore/MSSDK-1740: update pnpm install action for github actions call-publish

* chore/MSSDK-1740: use node@20 for call-publish

* chore/MSSDK-1740: use node@18 for call-publish

* chore/MSSDK-1740: use node@20 for call-publish

* chore/MSSDK-1740: add missing rimraf to dev dependencies

* chore/MSSDK-1740: cleanup verify_commit_message file

diff --git a/.husky/scripts/verify_commit_message b/.husky/scripts/verify_commit_message
--- a/.husky/scripts/verify_commit_message
+++ b/.husky/scripts/verify_commit_message
@@ -4,7 +4,7 @@ current_branch_name=$(git rev-parse --abbrev-ref HEAD)
 jira_id_regex="MSSDK-([[:digit:]]|external)+"
 jira_id=$(printf "$current_branch_name" | grep -Eo $jira_id_regex)
 
-current_commit_name=$(cat $HUSKY_GIT_PARAMS)
+current_commit_name=$1
 commit_name_regex="^(chore|docs|feat|fix|refactor|style|test)\/$jira_id:[[:space:]][[:alnum:]]+"
 merge_name_regex="^Merge[[:space:]]branch[[:space:]].*"
 commit_template="<type>/<jira-ticket-id>: <brief description>"
@@ -26,9 +26,9 @@ In the case of a merge, the name of commit should match the following template: 
 
 \n\nPlease rename your commit accordingly and try again.\n"
 
-if ! [[ "$current_commit_name" =~ (${commit_name_regex})|(${merge_name_regex}) ]]
+if ! (echo "$current_commit_name" | grep -Eq "$commit_name_regex|$merge_name_regex")
 then
-  echo -e $invalid_commit_message
+  echo "$invalid_commit_message"
   exit 1
 fi
 
